/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2015-06-08 05:04:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class listar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/shared/menu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- content -->\r\n");
      out.write("<div id=\"content\" class=\"app-content\" role=\"main\">\r\n");
      out.write("\t<div class=\"app-content-body \">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"bg-light lter b-b wrapper-md\">\r\n");
      out.write("\t\t\t<h1 class=\"m-n font-thin h3\">Usuários</h1>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"wrapper-md\">\r\n");
      out.write("\t\t\t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t\t\t<div class=\"panel-heading\">Usuários cadastrados no sistema</div>\r\n");
      out.write("\t\t\t\t<div class=\"panel-body b-b b-light\">\r\n");
      out.write("\t\t\t\t\tSearch: <input id=\"filter\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control input-sm w-sm inline m-r\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<table class=\"table m-b-none\" ui-jq=\"footable\"\r\n");
      out.write("\t\t\t\t\t\tdata-filter=\"#filter\" data-page-size=\"5\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-toggle=\"true\">Nome</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Email</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-hide=\"phone,tablet\">Perfil</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Ramal</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th data-hide=\"phone\">Opções</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Erick Wendel</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href>erick.workspace@gmail.com</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Administrador</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"78025368997\">11-2000</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"location.href='/callsystem/cadastrarRamal/1'\">+Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\" onclick=\"confirm('Deseja deletar ramal?')\">-Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Shona</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Woldt</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href>Airline Transport Pilot</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"370961043292\">3 Oct 1981</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">+Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\" >-Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Granville</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Leonardo</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Business Services Sales Representative</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"-22133780420\">19 Apr 1969</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">+Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\">-Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Easer</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Dragoo</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Drywall Stripper</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"250833505574\">13 Dec 1977</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">+Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\">-Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Maple</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Halladay</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Aviation Tactical Readiness Officer</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"694116650726\">30 Dec 1991</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">+Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\">-Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Maxine</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href>Woldt</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href>Business Services Sales Representative</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"561440464855\">17 Oct 1987</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">+Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\">-Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Lorraine</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Mcgaughy</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Hemodialysis Technician</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"437400551390\">11 Nov 1983</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">+Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\">-Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Lizzee</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td><a href>Goodlow</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Technical Services Librarian</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"-257733999319\">1 Nov 1961</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">+Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\">-Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Judi</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Badgett</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Electrical Lineworker</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"362134712000\">23 Jun 1981</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">+Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\">-Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Lauri</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Hyland</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>Blackjack Supervisor</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"500874333932\">15 Nov 1985</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td data-value=\"1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\">+Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-danger\">-Ramal</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t<tfoot class=\"hide-if-no-paging\">\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"5\" class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"pagination\"></ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- / content -->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/shared/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
